
[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
startup_mode = "Maximized"
option_as_alt = "Both"
decorations = "Buttonless"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 15 

[general]
import = [
	"~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]
